/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ys303.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 * This class handles the main function of the whole battleship app.
 */
public class App {
  /** TextPlayer A */
  TextPlayer player1;
  /** TextPlayer B */
  TextPlayer player2;

  /**
   * Constructor for App
   *
   * @param TextPlayer to initialize player1
   * @param TextPlayer to initialize player2
   */
  public App(TextPlayer p1, TextPlayer p2) {
    player1 = p1;
    player2 = p2;
  }

  /**
   * This method carries out the placement phase of the game. Player 1 puts 10
   * ships at first. Then player 2 puts.
   *
   * @throws EOFxception              when the input is empty.
   * @throws IllegalArgumentException when the placement is invalid.
   */
  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  /**
   * This method carries out the attacking phase of the game. Players alternate
   * turns starting with player 1. On a turn a player chooses and carries out an
   * action. The phase ends when one player has lost at which point this method
   * declares the winner by printing a message.
   *
   * @throws EOFxception              if get empty input.
   * @throws IllegalArgumentException if get invalid input.
   */
  public void doAttackingPhase() throws IOException {
    TextPlayer currentPlayer = player1;
    TextPlayer nextPlayer = player2;

    while (!currentPlayer.isLose()) {
      currentPlayer.playOneTurn(nextPlayer.theBoard, nextPlayer.view, "Your ocean",
          "Player " + nextPlayer.name + "'s ocean");
      TextPlayer temp = currentPlayer;
      currentPlayer = nextPlayer;
      nextPlayer = temp;
    }
    // currentPlayer lost, other player won
    nextPlayer.declareWinner(); // lets abstract this out into a method.
  }

  /**
   * Main of App
   *
   * Make a board, Ask two players to put their ships. Then each player alternate
   * to attack. Player 1 starts first.
   */
  public static void main(String[] args) throws IOException {
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();
    App app = new App(new TextPlayer("A", b1, input, System.out, factory),
        new TextPlayer("B", b2, input, System.out, factory));
    app.doPlacementPhase();
    app.doAttackingPhase();
  }
}
